apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kiss-frontend.fullname" . }}
  labels:
    {{- include "kiss-frontend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kiss-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kiss-frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kiss-frontend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: environment
        configMap:
          name: {{ include "kiss-frontend.fullname" . }}
          defaultMode: 420
      - name: kvk-certs-volume
        secret:
          secretName: kvk-certs
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - mountPath: /usr/share/nginx/html/env.js
            subPath: env.js
            name: environment
            readOnly: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:  # Add your environment variables here
          - name: OIDC_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: kiss-secrets
                key: OIDC_CLIENT_SECRET
          - name: KVK_API_KEY
            valueFrom:
              secretKeyRef:
                name: kiss-secrets
                key: KVK_API_KEY
          - name: HAAL_CENTRAAL_API_KEY
            valueFrom:
              secretKeyRef:
                name: kiss-secrets
                key: HAAL_CENTRAAL_API_KEY
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kiss-secrets
                key: POSTGRES_PASSWORD
          - name: ENTERPRISE_SEARCH_PUBLIC_API_KEY
            valueFrom:
              secretKeyRef:
                name: kiss-secrets
                key: ENTERPRISE_SEARCH_PUBLIC_API_KEY
          - name: ENTERPRISE_SEARCH_PRIVATE_API_KEY
            valueFrom:
              secretKeyRef:
                name: kiss-secrets
                key: ENTERPRISE_SEARCH_PRIVATE_API_KEY
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kiss-secrets
                key: ELASTIC_PASSWORD
          - name: ZAKEN_API_KEY
            valueFrom:
              secretKeyRef:
                name: kiss-secrets
                key: ZAKEN_API_KEY
          - name: KLANTEN_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: kiss-secrets
                key: KLANTEN_CLIENT_SECRET
          - name: EMAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kiss-secrets
                key: EMAIL_PASSWORD 
          - name: CONTACTMOMENTEN_API_KEY
            valueFrom:
              secretKeyRef:
                name: kiss-secrets
                key: CONTACTMOMENTEN_API_KEY 
          - name: CONTACTMOMENTEN_BASE_URL
            value: {{ .Values.env.CONTACTMOMENTEN_BASE_URL | quote }}
          - name: CONTACTMOMENTEN_API_CLIENT_ID
            value: {{ .Values.env.CONTACTMOMENTEN_API_CLIENT_ID | quote }}
          - name: OIDC_CLIENT_ID
            value: {{ .Values.env.OIDC_CLIENT_ID | quote }}
          - name: OIDC_AUTHORITY
            value: {{ .Values.env.OIDC_AUTHORITY | quote }}
          - name: KVK_BASE_URL
            value: {{ .Values.env.KVK_BASE_URL | quote }}
          - name: HAAL_CENTRAAL_BASE_URL
            value: {{ .Values.env.HAAL_CENTRAAL_BASE_URL | quote }}
          - name: POSTGRES_USER
            value: {{ .Values.env.POSTGRES_USER | quote }}
          - name: POSTGRES_DB
            value: {{ .Values.env.POSTGRES_DB | quote }}
          - name: POSTGRES_HOST
            value: {{ .Values.env.POSTGRES_HOST | quote }}
          - name: ASPNETCORE_ENVIRONMENT
            value: {{ .Values.env.ASPNETCORE_ENVIRONMENT | quote }}
          - name: ENTERPRISE_SEARCH_ENGINE
            value: {{ .Values.env.ENTERPRISE_SEARCH_ENGINE | quote }}
          - name: ENTERPRISE_SEARCH_BASE_URL
            value: {{ .Values.env.ENTERPRISE_SEARCH_BASE_URL | quote }}
          - name: ZAKEN_BASE_URL
            value: {{ .Values.env.ZAKEN_BASE_URL | quote }}
          - name: ZAKEN_API_CLIENT_ID
            value: {{ .Values.env.ZAKEN_API_CLIENT_ID | quote }}
          - name: KLANTEN_BASE_URL
            value: {{ .Values.env.KLANTEN_BASE_URL | quote }}
          - name: KLANTEN_CLIENT_ID
            value: {{ .Values.env.KLANTEN_CLIENT_ID | quote }}
          - name: EMAIL_HOST
            value: {{ .Values.env.EMAIL_HOST | quote }}
          - name: EMAIL_PORT
            value: {{ .Values.env.EMAIL_PORT | quote }}
          - name: EMAIL_USERNAME
            value: {{ .Values.env.EMAIL_USERNAME | quote }}
          - name: EMAIL_ENABLE_SSL
            value: {{ .Values.env.EMAIL_ENABLE_SSL | quote }}
          - name: FEEDBACK_EMAIL_FROM
            value: {{ .Values.env.FEEDBACK_EMAIL_FROM | quote }}
          - name: FEEDBACK_EMAIL_TO
            value: {{ .Values.env.FEEDBACK_EMAIL_TO | quote }}
          - name: ORGANISATIE_IDS
            value: {{ .Values.env.ORGANISATIE_IDS | quote }}
          - name: MEDEWERKER_OBJECTEN_BASE_URL
            value: {{ .Values.env.MEDEWERKER_OBJECTEN_BASE_URL | quote }}
          - name: MEDEWERKER_OBJECTEN_TOKEN
            value: {{ .Values.env.MEDEWERKER_OBJECTEN_TOKEN | quote }}
          - name: MEDEWERKER_OBJECTTYPES_BASE_URL
            value: {{ .Values.env.MEDEWERKER_OBJECTTYPES_BASE_URL | quote }}
          - name: MEDEWERKER_OBJECTTYPES_TOKEN
            value: {{ .Values.env.MEDEWERKER_OBJECTTYPES_TOKEN | quote }}
          - name: VAC_OBJECTEN_BASE_URL
            value: {{ .Values.env.VAC_OBJECTEN_BASE_URL | quote }}
          - name: VAC_OBJECTEN_TOKEN
            value: {{ .Values.env.VAC_OBJECTEN_TOKEN | quote }}
          - name: VAC_OBJECTTYPES_BASE_URL
            value: {{ .Values.env.VAC_OBJECTTYPES_BASE_URL | quote }}
          - name: VAC_OBJECTTYPES_TOKEN
            value: {{ .Values.env.VAC_OBJECTTYPES_TOKEN | quote }}
          - name: INTERNE_TAAK_BASE_URL
            value: {{ .Values.env.INTERNE_TAAK_BASE_URL | quote }}
          - name: INTERNE_TAAK_TOKEN
            value: {{ .Values.env.INTERNE_TAAK_TOKEN | quote }}
          - name: INTERNE_TAAK_OBJECT_TYPE_URL
            value: {{ .Values.env.INTERNE_TAAK_OBJECT_TYPE_URL | quote }}
          - name: AFDELINGEN_BASE_URL
            value: {{ .Values.env.AFDELINGEN_BASE_URL | quote }}
          - name: AFDELINGEN_TOKEN
            value: {{ .Values.env.AFDELINGEN_TOKEN | quote }}
          - name: AFDELINGEN_OBJECT_TYPE_URL
            value: {{ .Values.env.AFDELINGEN_OBJECT_TYPE_URL | quote }}
          - name: GROEPEN_BASE_URL
            value: {{ .Values.env.GROEPEN_BASE_URL | quote }}
          - name: GROEPEN_TOKEN
            value: {{ .Values.env.GROEPEN_TOKEN | quote }}
          - name: GROEPEN_OBJECT_TYPE_URL
            value: {{ .Values.env.GROEPEN_OBJECT_TYPE_URL | quote }}
          - name: ELASTIC_USERNAME
            value: {{ .Values.env.ELASTIC_USERNAME | quote }}
          - name: ELASTIC_BASE_URL
            value: {{ .Values.env.ELASTIC_BASE_URL | quote }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
