apiVersion: v1
entries:
  kiss-frontend:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-06-22T13:03:24.2794514+02:00"
    dependencies:
    - name: elasticstack
      repository: https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/Helm-Charts/feature/elastic-stack-chart/
      version: 0.4.4
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      tags:
      - postgresql
      version: 12.4.2
    description: A Helm chart for Kubernetes
    digest: 2160b16886572cfbc3c5b1f08621eb470c0933453345fb1c6cf629cd341daabe
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-1.0.40.tgz
    version: 1.0.40
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-06-22T13:03:24.2637687+02:00"
    dependencies:
    - name: elasticstack
      repository: https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/Helm-Charts/feature/elastic-stack-chart/
      version: 0.4.4
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      tags:
      - postgresql
      version: 12.4.2
    description: A Helm chart for Kubernetes
    digest: c04fcd993d8687e40e3602c3a86848d69c6a02093fbecad1028beff3ccd54390
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-1.0.39.tgz
    version: 1.0.39
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-06-22T13:03:24.2637687+02:00"
    dependencies:
    - name: elasticstack
      repository: https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/Helm-Charts/feature/elastic-stack-chart/
      version: 0.4.4
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      tags:
      - postgresql
      version: 12.4.2
    description: A Helm chart for Kubernetes
    digest: 2ddb76d3bcf8dccf1db76f64595adcb16ee692584a8c34d28978b23c24b9b4e2
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-1.0.38.tgz
    version: 1.0.38
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-06-22T13:03:24.2561335+02:00"
    dependencies:
    - name: elasticstack
      repository: https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/Helm-Charts/feature/elastic-stack-chart/
      version: 0.4.4
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      tags:
      - postgresql
      version: 12.4.2
    description: A Helm chart for Kubernetes
    digest: 1b1f28c1b8dba6e9fc4381d74f6f8a043cc37ddc2ab4b7566f0def8121165731
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-1.0.37.tgz
    version: 1.0.37
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-06-22T13:03:24.2482812+02:00"
    dependencies:
    - name: elasticstack
      repository: https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/Helm-Charts/feature/elastic-stack-chart/
      version: 0.4.4
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      tags:
      - postgresql
      version: 12.4.2
    description: A Helm chart for Kubernetes
    digest: e6ecceb7bcdc84f8a4fca35124c6377e139e879ee911256a825c5898d445e770
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-1.0.36.tgz
    version: 1.0.36
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-06-22T13:03:24.2330821+02:00"
    dependencies:
    - name: elasticstack
      repository: https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/Helm-Charts/feature/elastic-stack-chart/
      version: 0.4.4
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      tags:
      - postgresql
      version: 12.4.2
    description: A Helm chart for Kubernetes
    digest: c1529cc595e95ee3ab7a8b61bc4cd4088738c0fb68be978dfa6909d434c624cc
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-1.0.35.tgz
    version: 1.0.35
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-06-22T13:03:24.2230192+02:00"
    dependencies:
    - name: elasticstack
      repository: https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/Helm-Charts/feature/elastic-stack-chart/
      version: 0.4.4
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      tags:
      - postgresql
      version: 12.4.2
    description: A Helm chart for Kubernetes
    digest: 4dcf726b2d710fefdf36eedbe7d0b5aa317183188deeb9eb56b4c9e232375d9e
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-1.0.34.tgz
    version: 1.0.34
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-06-22T13:03:24.2178898+02:00"
    dependencies:
    - name: elasticstack
      repository: https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/Helm-Charts/feature/elastic-stack-chart/
      version: 0.4.4
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      tags:
      - postgresql
      version: 12.4.2
    description: A Helm chart for Kubernetes
    digest: 2e365cca3f519022d3d094910d6b7544a0a2230a99793f402ab879c42b60f3a4
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-1.0.33.tgz
    version: 1.0.33
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-06-22T13:03:24.2027304+02:00"
    dependencies:
    - name: elasticstack
      repository: https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/Helm-Charts/feature/elastic-stack-chart/
      version: 0.4.4
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      tags:
      - postgresql
      version: 12.4.2
    description: A Helm chart for Kubernetes
    digest: 255d361de1f21a36cf4ae4f1759bb8813f5dee3aa316e037094e972238eec295
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-1.0.32.tgz
    version: 1.0.32
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-06-22T13:03:24.2027304+02:00"
    dependencies:
    - name: elasticstack
      repository: https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/Helm-Charts/feature/elastic-stack-chart/
      version: 0.4.4
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      tags:
      - postgresql
      version: 12.4.2
    description: A Helm chart for Kubernetes
    digest: 5b11a229e7e643bd48e3e6e92324488e25253f519b9e76d062f2825314d78590
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-1.0.31.tgz
    version: 1.0.31
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-06-22T13:03:24.1925958+02:00"
    dependencies:
    - name: elasticstack
      repository: https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/Helm-Charts/feature/elastic-stack-chart/
      version: 0.4.4
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      tags:
      - postgresql
      version: 12.4.2
    description: A Helm chart for Kubernetes
    digest: a18e54cee44ffef12067271dd43926085e67d854b00c7d5966ff072f3bb35103
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-1.0.30.tgz
    version: 1.0.30
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-06-22T13:03:24.1860895+02:00"
    dependencies:
    - name: elasticstack
      repository: https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/Helm-Charts/feature/elastic-stack-chart/
      version: 0.4.4
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      tags:
      - postgresql
      version: 12.4.2
    description: A Helm chart for Kubernetes
    digest: bbd2948f3c3525c9e5e29a5c165da052778caf7c1992b9f415ee05d35bf10c97
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-1.0.29.tgz
    version: 1.0.29
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-06-22T13:03:24.1724844+02:00"
    dependencies:
    - name: elasticstack
      repository: https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/Helm-Charts/feature/elastic-stack-chart/
      version: 0.4.4
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      tags:
      - postgresql
      version: 12.4.2
    description: A Helm chart for Kubernetes
    digest: e861482bf4e5c66126c0cc0c7f54b9ea318dfb7e17e24b5bde2f5c412e64b6e0
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-1.0.28.tgz
    version: 1.0.28
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-06-22T13:03:24.1703823+02:00"
    dependencies:
    - name: elasticstack
      repository: https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/Helm-Charts/feature/elastic-stack-chart/
      version: 0.4.4
    description: A Helm chart for Kubernetes
    digest: 28f75a7fc3f54fa383b8f7839b751781b35d992d2111ea619f4c108d53d9bb3b
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-1.0.27.tgz
    version: 1.0.27
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-06-22T13:03:24.1623567+02:00"
    dependencies:
    - name: elasticstack
      repository: https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/Helm-Charts/feature/elastic-stack-chart/
      version: 0.4.4
    description: A Helm chart for Kubernetes
    digest: 4f2e2da123851a9dc34a6417d30dd3cca4befbe11aa5a04c4158b23fd43a62b5
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-1.0.26.tgz
    version: 1.0.26
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-06-22T13:03:24.1623567+02:00"
    dependencies:
    - name: elasticstack
      repository: https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/Helm-Charts/feature/elastic-stack-chart/
      version: 0.4.4
    description: A Helm chart for Kubernetes
    digest: 2b72afe713bd292e1ffabfe30dfba48f88c85e9fd1ac34a7c9aece689515bce6
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-1.0.25.tgz
    version: 1.0.25
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-06-22T13:03:24.1543488+02:00"
    dependencies:
    - name: elasticstack
      repository: https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/Helm-Charts/feature/elastic-stack-chart/
      version: 0.4.4
    description: A Helm chart for Kubernetes
    digest: 408275f217ab69bd982d6c4cc62315dcfaa731a8f94a75fa2e1103dcca9becd6
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-1.0.24.tgz
    version: 1.0.24
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-06-22T13:03:24.1543488+02:00"
    dependencies:
    - name: elasticstack
      repository: https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/Helm-Charts/feature/elastic-stack-chart/
      version: 0.4.4
    description: A Helm chart for Kubernetes
    digest: 4035d56fff863856925ad74d45020a0305eeabdcf22b68971eb426a61ae203f2
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-1.0.23.tgz
    version: 1.0.23
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-06-22T13:03:24.1422413+02:00"
    dependencies:
    - name: elasticstack
      repository: https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/Helm-Charts/feature/elastic-stack-chart/
      version: 0.4.4
    description: A Helm chart for Kubernetes
    digest: f81582ccf6cc229bf3d2056429d77b67b76da1e80eb088f67d3e4f530d261c90
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-1.0.22.tgz
    version: 1.0.22
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-06-22T13:03:24.1422413+02:00"
    dependencies:
    - name: elasticstack
      repository: https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/Helm-Charts/feature/elastic-stack-chart/
      version: 0.4.4
    description: A Helm chart for Kubernetes
    digest: 17036b0a431f45c6568cdea6d7ea6525a3a5d6a6b8b3d9af53d20bce43f63754
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-1.0.21.tgz
    version: 1.0.21
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-06-22T13:03:24.1385995+02:00"
    dependencies:
    - name: elasticstack
      repository: https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/Helm-Charts/feature/elastic-stack-chart/
      version: 0.4.4
    description: A Helm chart for Kubernetes
    digest: 7c50ceead04192f7654d31be556ed27afe484dcfcbdc4b743614ecf8cb7395b3
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-1.0.20.tgz
    version: 1.0.20
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-06-22T13:03:24.1320574+02:00"
    dependencies:
    - name: elasticstack
      repository: https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/Helm-Charts/feature/elastic-stack-chart/
      version: 0.4.4
    description: A Helm chart for Kubernetes
    digest: e96b979236bcb104aa89d0c530c969c50325d13f6c6969f1231add05fa7e288f
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-1.0.19.tgz
    version: 1.0.19
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-06-22T13:03:24.1117559+02:00"
    dependencies:
    - name: elasticstack
      repository: https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/Helm-Charts/feature/elastic-stack-chart/
      version: 0.4.4
    description: A Helm chart for Kubernetes
    digest: 1c4d585c915bc17f27def9c93b000d492981470b4f927b813f4708eded5eb9ec
    name: kiss-frontend
    type: application
    urls:
    - kiss-frontend-1.0.18.tgz
    version: 1.0.18
generated: "2023-06-22T13:03:24.067718+02:00"
